### ISSUE TITLE
Add SEO settings to each Page

### ISSUE THREAD

**Issue by webriq** [webriq-pagebuilder/studio-template-default#3]
![image](https://user-images.githubusercontent.com/6467262/121619846-d8255900-ca9b-11eb-8662-e156015a8107.png)
 
After **Sections** should have a **SEO Settings** section where we could configure all necessary SEO settings for a given page.

**Comment by mamfi-0221** [comment]
Opened new PR with implementation of SEO settings using the [sanity-seo-pane](https://www.npmjs.com/package/sanity-plugin-seo-pane) plugin.
