### ISSUE TITLE
Fix SEO Analysis

### ISSUE THREAD

**Issue by webriq** [webriq-pagebuilder/studio-template-default#4]
Should go with [task](https://github.com/webriq-pagebuilder/studio-template-default/issues/3). SEO meta tags should be properly placed.

**Comment by mamfi-0221** [comment]
With recent updates on SEO settings, preview needs fixing
![image](https://user-images.githubusercontent.com/78787873/122856674-c40a1300-d349-11eb-97f8-458d13a83e6d.png)

**Comment by mamfi-0221** [comment]
> With recent updates on SEO settings, preview needs fixing
> ![image](https://user-images.githubusercontent.com/78787873/122856674-c40a1300-d349-11eb-97f8-458d13a83e6d.png)

Updated the [plugin](https://www.npmjs.com/package/sanity-plugin-seo-pane) to recent version
![image](https://user-images.githubusercontent.com/78787873/122872530-27ed0580-d363-11eb-9e3a-6a61f59ee994.png)

**Comment by mamfi-0221** [comment]
Fixed in approved [pull request](https://github.com/webriq-pagebuilder/studio-template-default/pull/19)
